# Generated by Django 4.0.3 on 2022-04-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbase', '0002_project_author_alter_college_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='docfile',
            field=models.FileField(default='DEFAULT VALUE', upload_to='documents/%d/%m/%Y'),
        ),
    ]
