# Generated by Django 4.0.3 on 2022-04-28 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbase', '0004_message_programme_repository_remove_course_project_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='course',
            new_name='programme',
        ),
    ]
