# Generated by Django 4.0.3 on 2022-04-28 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbase', '0005_rename_course_department_programme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
