# Generated by Django 4.0.3 on 2022-04-28 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srbase', '0006_delete_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='programme',
        ),
        migrations.AddField(
            model_name='repository',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='srbase.department'),
        ),
        migrations.DeleteModel(
            name='Programme',
        ),
    ]
