# Generated by Django 4.0.3 on 2022-05-02 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbase', '0007_remove_department_programme_repository_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='department',
        ),
    ]
