# Generated by Django 4.0.3 on 2022-05-08 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srbase', '0008_remove_college_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='college',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='department',
        ),
        migrations.AddField(
            model_name='college',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='srbase.department'),
        ),
        migrations.AddField(
            model_name='department',
            name='reposiotry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='srbase.repository'),
        ),
    ]
