# Generated by Django 4.0.3 on 2022-05-08 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srbase', '0009_remove_repository_college_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='reposiotry',
        ),
        migrations.AddField(
            model_name='department',
            name='repository',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='srbase.repository'),
        ),
    ]
