# Generated by Django 4.0.3 on 2022-05-08 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srbase', '0011_college_repository'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='repository',
        ),
        migrations.RemoveField(
            model_name='department',
            name='repository',
        ),
        migrations.AddField(
            model_name='repository',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='srbase.college'),
        ),
        migrations.AddField(
            model_name='repository',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='srbase.department'),
        ),
    ]
