# Generated by Django 4.0.3 on 2022-05-09 01:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('srbase', '0014_remove_college_department_department_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='author',
        ),
        migrations.AddField(
            model_name='repository',
            name='author',
            field=models.ManyToManyField(blank=True, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
