# Generated by Django 4.0.3 on 2022-05-09 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('srbase', '0015_remove_repository_author_repository_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='authors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='repository',
            name='author',
        ),
        migrations.AddField(
            model_name='repository',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
