# Generated by Django 4.0.4 on 2022-05-19 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbase', '0016_repository_authors_remove_repository_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
