# Generated by Django 4.0.4 on 2022-05-23 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srbase', '0017_remove_repository_department_delete_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='srbase.college'),
        ),
    ]
